version: 2.1
executors: 
  docker-publisher: 
    environment: 
      REPOSITORY: test_deploy
      IMAGE_NAME: sample
      VERSION: latest
    docker: 
      - image: mcr.microsoft.com/dotnet/core/aspnet:3.0
commands: 
  install-docker: 
    description: "Intsalling docker which is not represented in ASP.NET image"
    steps: 
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
jobs: 
  build:
    executor: docker-publisher
    steps: 
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      - install-docker 
      - run: 
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME .
      - run: 
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace: 
          root: .
          paths: 
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace: 
          at: /tmp/workspace
      - setup_remote_docker: 
          docker_layer_caching: true
      - install-docker 
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to GitHub
          command: |
            REGISTRY_HTTP_RELATIVEURLS=true
            docker login docker.pkg.github.com -u "$GITHUB_USERNAME" -p "$GITHUB_PUBLISH_TOKEN"
            docker tag $IMAGE_NAME docker.pkg.github.com/$GITHUB_USERNAME/$REPOSITORY/$IMAGE_NAME:$VERSION
            docker push docker.pkg.github.com/$GITHUB_USERNAME/$REPOSITORY/$IMAGE_NAME:$VERSION
workflows: 
  version: 2
  build-master: 
    jobs: 
      - build: 
          filters: 
            branches: 
              only: master
      - publish-latest: 
          requires: 
            - build
          filters: 
            branches: 
              only: master
